[package]
name = "fj-proc"
version = "0.11.0"
edition = "2021"

description = """\
Early-stage, next-generation, code-first CAD application. Because the world \
needs another CAD program.\
"""
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1.0.42"
quote = "1.0.20"

[dependencies.serde]
version = "1.0.140"
optional = true

[dependencies.syn]
version = "1.0.98"
features = ["full", "extra-traits"]

[dev-dependencies]
fj = { path = "../fj" }
