[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
map-macro = "0.2.5"
octocrab = "0.20.0"
semver = "1.0.17"
serde = "1.0.159"
serde_json = "1.0.95"
url = "2.3.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.2.2"
features = ["derive"]

[dependencies.tokio]
version = "1.27.0"
features = ["full"]
