[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
map-macro = "0.3.0"
octocrab = "0.38.0"
semver = "1.0.23"
serde = "1.0.203"
serde_json = "1.0.117"
tracing = "0.1.40"
url = "2.5.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.5.4"
features = ["derive"]

[dependencies.tokio]
version = "1.38.0"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
