[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.72"
chrono = "0.4.26"
map-macro = "0.2.6"
octocrab = "0.29.0"
semver = "1.0.18"
serde = "1.0.175"
serde_json = "1.0.103"
url = "2.4.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.3.19"
features = ["derive"]

[dependencies.tokio]
version = "1.29.1"
features = ["full"]
