[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.78"
chrono = "0.4.34"
map-macro = "0.3.0"
octocrab = "0.34.1"
semver = "1.0.21"
serde = "1.0.196"
serde_json = "1.0.113"
tracing = "0.1.40"
url = "2.5.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.5.0"
features = ["derive"]

[dependencies.tokio]
version = "1.36.0"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
