[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.64"
chrono = "0.4.22"
map-macro = "0.2.4"
octocrab = "0.17.0"
url = "2.2.2"

[dependencies.clap]
version = "3.2.17"
features = ["derive"]

[dependencies.tokio]
version = "1.20.1"
features = ["full"]
