[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
map-macro = "0.2.6"
octocrab = "0.25.1"
semver = "1.0.17"
serde = "1.0.165"
serde_json = "1.0.100"
url = "2.4.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.3.11"
features = ["derive"]

[dependencies.tokio]
version = "1.29.1"
features = ["full"]
