[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
map-macro = "0.2.6"
octocrab = "0.31.2"
semver = "1.0.20"
serde = "1.0.190"
serde_json = "1.0.107"
url = "2.4.1"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.tokio]
version = "1.33.0"
features = ["full"]
