[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
map-macro = "0.2.4"
octocrab = "0.17.0"
semver = "1.0.14"
serde = "1.0.147"
serde_json = "1.0.89"
url = "2.3.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.0.26"
features = ["derive"]

[dependencies.tokio]
version = "1.22.0"
features = ["full"]
