[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
map-macro = "0.3.0"
octocrab = "0.42.1"
semver = "1.0.24"
serde = "1.0.217"
serde_json = "1.0.134"
tracing = "0.1.41"
url = "2.5.4"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.5.23"
features = ["derive"]

[dependencies.tokio]
version = "1.42.0"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter"]
