[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
map-macro = "0.2.6"
octocrab = "0.21.0"
semver = "1.0.17"
serde = "1.0.163"
serde_json = "1.0.96"
url = "2.3.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "4.2.7"
features = ["derive"]

[dependencies.tokio]
version = "1.28.0"
features = ["full"]
