[package]
name = "automator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
map-macro = "0.2.4"
octocrab = "0.17.0"
semver = "1.0.13"
serde_json = "1.0.85"
url = "2.3.0"

[dependencies.autolib]
path = "../autolib"

[dependencies.clap]
version = "3.2.20"
features = ["derive"]

[dependencies.tokio]
version = "1.21.0"
features = ["full"]
