[package]
name = "fj-operations"
version = "0.16.0"
edition = "2021"

description = """\
Early-stage, next-generation, code-first CAD application. Because the world \
needs another CAD program.\
"""
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
thiserror = "1.0.35"

[dependencies.fj]
version = "0.16.0"
path = "../fj"

[dependencies.fj-math]
version = "0.16.0"
path = "../fj-math"

[dependencies.fj-interop]
version = "0.16.0"
path = "../fj-interop"

[dependencies.fj-kernel]
version = "0.16.0"
path = "../fj-kernel"
