[package]
name = "fj-window"
version = "0.7.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
futures = "0.3.21"
thiserror = "1.0.31"
tracing = "0.1.35"
winit = "0.26.1"

[dependencies.fj-host]
version = "0.7.0"
path = "../fj-host"

[dependencies.fj-operations]
version = "0.7.0"
path = "../fj-operations"

[dependencies.fj-viewer]
version = "0.7.0"
path = "../fj-viewer"
