[package]
name = "fj-window"
version = "0.12.0"
edition = "2021"

description = """\
Early-stage, next-generation, code-first CAD application. Because the world \
needs another CAD program.\
"""
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
futures = "0.3.23"
thiserror = "1.0.32"
tracing = "0.1.35"
winit = "0.27.2"

[dependencies.fj-host]
version = "0.12.0"
path = "../fj-host"

[dependencies.fj-operations]
version = "0.12.0"
path = "../fj-operations"

[dependencies.fj-viewer]
version = "0.12.0"
path = "../fj-viewer"

[dependencies.fj-interop]
version = "0.12.0"
path = "../fj-interop"
