[package]
name = "fj"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[build-dependencies]
anyhow = "1.0.66"


[dependencies]
fj-proc.workspace = true

[dependencies.serde]
version = "1.0.147"
features = ["derive"]
optional = true

[dev-dependencies]
serde_json = "1.0.87"
