[package]
name = "fj"
version = "0.9.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
serde = { version = "1.0.139", features = ["derive"], optional = true }

[dependencies.fj-proc]
version = "0.9.0"
path = "../../crates/fj-proc"

[dev-dependencies]
serde_json = "1.0.82"
