[package]
name = "fj"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[dependencies]
fj-core.workspace = true
fj-export.workspace = true
fj-interop.workspace = true
fj-math.workspace = true
fj-viewer.workspace = true
fj-window.workspace = true
thiserror = "1.0.44"

[dependencies.clap]
version = "4.3.21"
features = ["derive"]
