[package]
name = "fj"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true


[dependencies]
fj-core.workspace = true
fj-export.workspace = true
fj-interop.workspace = true
fj-math.workspace = true
fj-viewer.workspace = true
fj-window.workspace = true
thiserror = "2.0.3"
tracing = "0.1.41"

[dependencies.clap]
version = "4.5.21"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter"]
