[package]
name = "fj-math"
version = "0.5.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]

[dependencies]
approx = "0.5.1"
decorum = "0.3.1"
nalgebra = "0.31.0"
num-traits = "0.2.14"
parry2d-f64 = "0.9.0"
parry3d-f64 = "0.9.0"
