[package]
name = "all"
version = "0.1.0"
edition = "2021"

[dependencies.fj]
path = "../../crates/fj"

[dependencies.cuboid]
path = "../cuboid"

[dependencies.spacer]
path = "../spacer"

[dependencies.star]
path = "../star"
