[package]
name = "fj-core"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fj-interop.workspace = true
fj-math.workspace = true
iter_fixed = "0.3.1"
itertools = "0.11.0"
parking_lot = "0.12.0"
robust = "1.1.0"
spade = "2.2.0"
thiserror = "1.0.48"
type-map = "0.5.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
anyhow = "1.0.75"
