[package]
name = "fj-kernel"
version = "0.7.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
anymap = "1.0.0-beta.2"
map-macro = "0.2.2"
parking_lot = "0.12.0"
robust = "0.2.3"
slotmap = "1.0.6"
spade = "2.0.0"
thiserror = "1.0.31"

[dependencies.fj-interop]
version = "0.7.0"
path = "../fj-interop"

[dependencies.fj-math]
version = "0.7.0"
path = "../fj-math"


[dev-dependencies]
anyhow = "1.0.58"
pretty_assertions = "1.2.1"
