[package]
name = "fj-export"
version = "0.14.0"
edition = "2021"

description = """\
Early-stage, next-generation, code-first CAD application. Because the world \
needs another CAD program.\
"""
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
thiserror = "1.0.34"
threemf = "0.3.1"
stl = "0.2.1"

[dependencies.fj-interop]
version = "0.14.0"
path = "../fj-interop"

[dependencies.fj-math]
version = "0.14.0"
path = "../fj-math"
