[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.80"
cargo_metadata = "0.18.1"
cmd_lib = "1.9.3"
env_logger = "0.11.2"
log = "0.4.20"
secstr = "0.5.0"
semver = "1.0.22"
serde_json = "1.0.114"
thiserror = "1.0.57"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.24"
features = ["blocking"]

[dependencies.clap]
version = "4.5.1"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.197"
features = ["derive"]
