[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.72"
cargo_metadata = "0.17.0"
cmd_lib = "1.3.0"
env_logger = "0.10.0"
log = "0.4.19"
secstr = "0.5.0"
semver = "1.0.18"
serde_json = "1.0.103"
thiserror = "1.0.44"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.18"
features = ["blocking"]

[dependencies.clap]
version = "4.3.19"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.175"
features = ["derive"]
