[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.70"
cargo_metadata = "0.15.3"
cmd_lib = "1.3.0"
env_logger = "0.10.0"
log = "0.4.17"
secstr = "0.5.0"
semver = "1.0.17"
serde_json = "1.0.94"
thiserror = "1.0.40"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.16"
features = ["blocking"]

[dependencies.clap]
version = "4.1.11"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.158"
features = ["derive"]
