[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.66"
cargo_metadata = "0.15.2"
cmd_lib = "1.3.0"
env_logger = "0.9.2"
log = "0.4.17"
secstr = "0.5.0"
semver = "1.0.14"
serde_json = "1.0.89"
thiserror = "1.0.35"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.13"
features = ["blocking"]

[dependencies.clap]
version = "4.0.26"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.147"
features = ["derive"]
