[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.97"
cargo_metadata = "0.19.2"
cmd_lib = "1.9.5"
env_logger = "0.11.6"
log = "0.4.27"
secstr = "0.5.0"
semver = "1.0.26"
serde_json = "1.0.140"
thiserror = "2.0.12"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.12.14"
features = ["blocking"]

[dependencies.clap]
version = "4.5.34"
features = ["std", "derive", "env"]
default-features = false

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
