[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.86"
cargo_metadata = "0.18.1"
cmd_lib = "1.9.4"
env_logger = "0.11.5"
log = "0.4.22"
secstr = "0.5.0"
semver = "1.0.23"
serde_json = "1.0.121"
thiserror = "1.0.63"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.12.4"
features = ["blocking"]

[dependencies.clap]
version = "4.5.11"
features = ["std", "derive", "env"]
default-features = false

[dependencies.serde]
version = "1.0.204"
features = ["derive"]
