[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.78"
cargo_metadata = "0.18.1"
cmd_lib = "1.9.3"
env_logger = "0.10.2"
log = "0.4.20"
secstr = "0.5.0"
semver = "1.0.21"
serde_json = "1.0.111"
thiserror = "1.0.53"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.23"
features = ["blocking"]

[dependencies.clap]
version = "4.4.18"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.195"
features = ["derive"]
