[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.75"
cargo_metadata = "0.18.1"
cmd_lib = "1.8.0"
env_logger = "0.10.0"
log = "0.4.20"
secstr = "0.5.0"
semver = "1.0.20"
serde_json = "1.0.108"
thiserror = "1.0.50"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.11.20"
features = ["blocking"]

[dependencies.clap]
version = "4.4.7"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.190"
features = ["derive"]
