[package]
name = "release-operator"
version = "0.3.1"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0.82"
cargo_metadata = "0.18.1"
cmd_lib = "1.9.3"
env_logger = "0.11.3"
log = "0.4.21"
secstr = "0.5.0"
semver = "1.0.22"
serde_json = "1.0.116"
thiserror = "1.0.59"

[dependencies.autolib]
path = "../autolib"

[dependencies.reqwest]
version = "0.12.4"
features = ["blocking"]

[dependencies.clap]
version = "4.5.4"
features = ["std", "derive", "env"]
default_features = false

[dependencies.serde]
version = "1.0.198"
features = ["derive"]
