[package]
name = "fj-host"
version = "0.8.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
libloading = "0.7.2"
notify = "5.0.0-pre.15"
thiserror = "1.0.31"
cargo_metadata = "0.15.0"

[dependencies.fj]
version = "0.8.0"
path = "../fj"
