[package]
name = "fj-host"
version = "0.11.0"
edition = "2021"

description = """\
Early-stage, next-generation, code-first CAD application. Because the world \
needs another CAD program.\
"""
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
libloading = "0.7.2"
notify = "5.0.0-pre.15"
thiserror = "1.0.31"
cargo_metadata = "0.15.0"

[dependencies.fj]
version = "0.11.0"
path = "../fj"

[dependencies.fj-interop]
version = "0.11.0"
path = "../fj-interop"
