[package]
name = "fj-app"
version = "0.5.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../README.md"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
anyhow = "1.0.57"

[dependencies.clap]
version = "3.1.14"
features = ["derive"]

[dependencies.figment]
version = "0.10.6"
features = ["env", "toml"]

[dependencies.fj]
version = "0.5.0"
path = "../fj"

[dependencies.fj-export]
version = "0.5.0"
path = "../fj-export"

[dependencies.fj-host]
version = "0.5.0"
path = "../fj-host"

[dependencies.fj-kernel]
version = "0.5.0"
path = "../fj-kernel"

[dependencies.fj-math]
version = "0.5.0"
path = "../fj-math"

[dependencies.fj-operations]
version = "0.5.0"
path = "../fj-operations"

[dependencies.fj-viewer]
version = "0.5.0"
path = "../fj-viewer"

[dependencies.serde]
version = "1.0.137"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.11"
features = ["env-filter", "fmt"]
