name: Continuous Deployment

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

  # Name of the crate from Cargo.toml
  # used to rename and upload the binaries
  PROJ_NAME: fj-app

jobs:
  binaries:
    name: Binaries
    strategy:
      matrix:
        include:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macOS-latest }
          - { target: aarch64-apple-darwin, os: macOS-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Binaries | Compile
        uses: actions-rs/cargo@v1
        with:
          args: --release --target ${{ matrix.target }}
          command: build

      - name: Binaries | Prepare upload
        run: |
          # Include compile target in binary name

          src="target/${{ matrix.target }}/release/${PROJ_NAME}"
          dst="${GITHUB_WORKSPACE}/${PROJ_NAME}-${{ matrix.target }}"

          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            src="${src}.exe"
            dst="${dst}.exe"
          fi

          mv -v "${src}" "${dst}"
          chmod -v +x "${dst}"

      - name: Binaries | Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJ_NAME }}-${{ matrix.target }}
          path: ${{ env.PROJ_NAME }}-*
